---
title: "Figure 2"
author: "Emily Kubota"
date: "7/25/2024"
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE}
library("tidyverse") # for all things tidyverse
library("patchwork") # for subplots
library("viridis")
library("ggcorrplot") # for correlation plots



# set the default ggplot theme 
theme_set(theme_classic())



```

```{r}
# Read in the data 

df = read_csv("../../data/pca.csv",
              col_types = cols())
df_accuracy = read_csv("../../data/df_accuracy.csv",
                       col_types = cols())

```


```{r}
# PC plot for cyto 

df %>% 
  mutate(PC1 = pc1,
         PC2 = pc2,
         Cyto = cyto) %>% 
  ggplot(aes(x=PC1,y=PC2,color=Cyto)) +
  geom_point(alpha = .5,
             shape = 1) +
  scale_color_manual(values=c("cyan","green","magenta")) +
  ggtitle("Cyto") +
  theme(aspect.ratio=1,
        legend.position="none",
        axis.line=element_blank(),
        #axis.text.x=element_blank(),
        #axis.text.y=element_blank(),
        axis.ticks=element_blank()) +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) 

outpath='../../figures/fig2/'
   ggsave(
      filename =
        paste0(outpath, 'fig2_cyto.pdf'),
      width = 2,
      height = 2
    )

```




```{r}

# PC plot for category 

 df %>% 
  mutate(PC1 = pc1,
         PC2 = pc2,
         Category = as.factor(category)) %>% 
  mutate(Category = fct_relevel(Category, c("face","word","body","place"))) %>% 
  ggplot(aes(x=PC1,y=PC2,color=Category)) +
  geom_point(alpha = .5,
              shape = 1) +
  scale_color_manual(values=c("red","blue","#ffd900","#007f00")) +
  ggtitle("Category") +
  theme(aspect.ratio=1,
        legend.position="none",
        axis.line=element_blank(),
        #axis.text.x=element_blank(),
        #axis.text.y=element_blank(),
        axis.ticks=element_blank()) +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) 

outpath='../../figures/fig2/'
   ggsave(
      filename =
        paste0(outpath, 'fig2_category.pdf'),
      width = 2,
      height = 2
    )

```

```{r}

# PC plot for age 
 df %>% 
  mutate(PC1 = pc1,
         PC2 = pc2,
         Age = recode(age,
                      'mri0'='0 months',
                      'mri3'='3 months',
                      'mri6'='6 months',
                      'adult_multishell'='Adults')) %>% 
   mutate(Age = fct_relevel(Age, c("0 months","3 months","6 months","Adults"))) %>% 
  ggplot(aes(x=PC1,y=PC2,color=Age)) +
  geom_point(alpha = .5,
             shape = 1) +
   ggtitle("Age") +
  theme(aspect.ratio=1,
        legend.position="none",
        axis.line=element_blank(),
        #axis.text.x=element_blank(),
        #axis.text.y=element_blank(),
        axis.ticks=element_blank()) +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) 


  outpath='../../figures/fig2/'
   ggsave(
      filename =
        paste0(outpath, 'fig2_age.pdf'),
      width = 2,
      height = 2
    )


``` 




