---
title: "Figure 2"
author: "Emily Kubota"
date: "7/25/2024"
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE}
library("tidyverse") # for all things tidyverse
library("patchwork") # for subplots


# these options here change the formatting of how comments are rendered
opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")

# set the default ggplot theme 
theme_set(theme_classic())


```

```{r}
# Read in the data 

df = read_csv("../../data/pca.csv",
              col_types = cols())
df_accuracy = read_csv("../../data/df_accuracy.csv",
                       col_types = cols())

```


```{r}
# PC plot for cyto 

 a <- df %>% 
  mutate(PC1 = pc1,
         PC2 = pc2,
         Cyto = cyto) %>% 
  ggplot(aes(x=PC1,y=PC2,color=Cyto)) +
  geom_point(alpha = .5,
             shape = 1) +
  scale_color_manual(values=c("cyan","green","magenta")) +
  ggtitle("Cyto") +
  theme(aspect.ratio=1,
        legend.position="none",
        axis.line=element_blank(),
        #axis.text.x=element_blank(),
        #axis.text.y=element_blank(),
        axis.ticks=element_blank()) +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) 


```


```{r}

# PC plot for category 

b <- df %>% 
  mutate(PC1 = pc1,
         PC2 = pc2,
         Category = as.factor(category)) %>% 
  mutate(Category = fct_relevel(Category, c("face","word","body","place"))) %>% 
  ggplot(aes(x=PC1,y=PC2,color=Category)) +
  geom_point(alpha = .5,
              shape = 1) +
  scale_color_manual(values=c("red","blue","#ffd900","#007f00")) +
  ggtitle("Category") +
  theme(aspect.ratio=1,
        legend.position="none",
        axis.line=element_blank(),
        #axis.text.x=element_blank(),
        #axis.text.y=element_blank(),
        axis.ticks=element_blank()) +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) 


```

```{r}

# PC plot for age 

c <- df %>% 
  mutate(PC1 = pc1,
         PC2 = pc2,
         Age = recode(age,
                      'mri0'='0 months',
                      'mri3'='3 months',
                      'mri6'='6 months',
                      'adult_multishell'='Adults')) %>% 
   mutate(Age = fct_relevel(Age, c("0 months","3 months","6 months","Adults"))) %>% 
  ggplot(aes(x=PC1,y=PC2,color=Age)) +
  geom_point(alpha = .5,
             shape = 1) +
   ggtitle("Age") +
  theme(aspect.ratio=1,
        legend.position="none",
        axis.line=element_blank(),
        #axis.text.x=element_blank(),
        #axis.text.y=element_blank(),
        axis.ticks=element_blank()) +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) 


``` 

```{r}

# Classification accuracy plot for cyto 

d <-  df_accuracy %>% 
  filter(classifcation == "cyto") %>% 
  mutate(Accuracy = as.numeric(accuracy)) %>% 
  ggplot(aes(x=true_label,y=Accuracy,fill = true_label)) +
    stat_summary(fun = "mean",
                 geom = "bar") +
    stat_summary(
      fun.data = "mean_se",
      geom = "linerange",
      size = 1,
      color = "black"
    ) +
  scale_fill_manual(values=c("cyan","green","magenta")) +
  ggtitle("Cyto") +
  xlab("") +
  geom_hline(yintercept = .33, linetype = 2) +
  theme(aspect.ratio=1,
        legend.position="none") +
    coord_cartesian(ylim = c(0,1))


```


```{r}
# Classification accuracy plot for category 

e <- df_accuracy %>% 
  filter(classifcation == "category") %>% 
  mutate(Accuracy = as.numeric(accuracy),
         true_label = fct_relevel(true_label, c("face","word","body","place"))) %>% 
  ggplot(aes(x=true_label,y=Accuracy,fill = true_label)) +
    stat_summary(fun = "mean",
                 geom = "bar") +
    stat_summary(
      fun.data = "mean_se",
      geom = "linerange",
      size = 1,
      color = "black"
    ) +
  scale_fill_manual(values=c("red","blue","#ffd900","#007f00")) +
  ggtitle("Category") +
  xlab("") +
  geom_hline(yintercept = .25, linetype = 2) +
  theme(aspect.ratio=1,
        legend.position="none") +
  coord_cartesian(ylim = c(0,1))


```


```{r}

# Classification accuracy plot for age 

f <- df_accuracy %>% 
  filter(classifcation == "age") %>% 
  mutate(Accuracy = as.numeric(accuracy),
          true_label = recode(true_label,
                      '0 months'='0M',
                      '3 months'='3M',
                      '6 months'='6M',
                      'adult_multishell'='Adults')) %>% 
   mutate(true_label = fct_relevel(true_label, c("0M","3M","6M","Adults"))) %>% 
  ggplot(aes(x=true_label,y=Accuracy,fill = true_label)) +
    stat_summary(fun = "mean",
                 geom = "bar") +
    stat_summary(
      fun.data = "mean_se",
      geom = "linerange",
      size = 1,
      color = "black"
    ) +
  ggtitle("Age") +
  xlab("") +
  geom_hline(yintercept = .25, linetype = 2) +
  theme(aspect.ratio=1,
        legend.position="none") +
  coord_cartesian(ylim = c(0,1))
```

```{r}
b+a+c+e+d+f

outpath='../../figures/fig2/'
   ggsave(
      filename =
        paste0(outpath, 'fig2.png'),
      width = 6,
      height = 4
    )

```

