---
title: "Classification"
author: "Emily Kubota"
date: "7/26/2024"
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE}
library("tidyverse") # for all things tidyverse

```

```{r}
dataPath = "../../data/pca.csv"

df = read_csv(dataPath,
              col_types = cols())

```


```{r}
# get the subject name
df <-
df %>% 
  mutate(subject_name = str_split_i(sub,'_',1))

```


```{r}
# Category classification 

predicted_category = c()

for (i in 1:nrow(df)){
 
  # test df is the held out row only 
  test_df <- df[c(i), ]
  
  # train_df is all of the data minus the held out subjects data 
   train_df <- df %>% 
    filter(subject_name != test_df$subject_name)
   
  # fit your model
  model <- multinom(category ~ pc1 + pc2 + pc3 + pc4 + pc5 + pc6 + pc7 + pc8 + pc9 + pc10, data = train_df)
  # make prediction for the held out data  
  df_pred = predict(model, newdata = test_df, "probs")

  foo <- df_pred[which.max(df_pred)]
  predicted_category[i] <- names(foo)
}

df$predicted_category <- predicted_category

```

```{r}
# Cyto classification 
predicted_cyto = c()

for (i in 1:nrow(df)){
  # test df is the held out row only 
  test_df <- df[c(i), ]
  # train_df is all of the data minus the held out subjects data 
  train_df <- df %>% 
    filter(subject_name != test_df$subject_name)
  # fit your model
  model <- multinom(cyto ~ pc1 + pc2 + pc3 + pc4 + pc5 + pc6 + pc7 + pc8 + pc9 + pc10, data = train_df)
  # make prediction for the held out data  
  df_pred = predict(model, newdata = test_df, "probs")

  foo <- df_pred[which.max(df_pred)]
  predicted_cyto[i] <- names(foo)
}

df$predicted_cyto <- predicted_cyto

```


```{r}
# Age classification 

df <- 
  df %>% 
  mutate(Age = recode(age,
                      'mri0' = '0 months',
                      'mri3' = '3 months',
                      'mri6' = '6 months',
                      'adult_multishell' = 'Adults'))

predicted_age = c()

for (i in 1:nrow(df)){
  # test df is the held out row only 
  test_df <- df[c(i), ]
  
  # train_df is all of the data minus the held out subjects data 
   train_df <- df %>% 
    filter(subject_name != test_df$subject_name)
   
  # fit your model
  model <- multinom(Age ~ pc1 + pc2 + pc3 + pc4 + pc5 + pc6 + pc7 + pc8 + pc9 + pc10, data = train_df)
  # make prediction for the held out data  
  df_pred = predict(model, newdata = test_df, "probs")

  foo <- df_pred[which.max(df_pred)]
  predicted_age[i] <- names(foo)
}

df$predicted_age <- predicted_age

```


```{r}

# Compute classification accuracy 

age_accuracy <-
  df %>% 
  mutate(accuracy = predicted_age == Age,
         true_label = Age,
         predicted_label = predicted_age) %>% 
  select(accuracy,age,subject_name,sub,true_label,predicted_label) %>% 
  mutate(classifcation='age')

cyto_accuracy <-
  df %>% 
  mutate(accuracy = predicted_cyto == cyto,
         true_label = cyto,
         predicted_label = predicted_cyto) %>% 
  select(accuracy,age,subject_name,sub,true_label,predicted_label) %>% 
  mutate(classifcation='cyto')

category_accuracy <-
  df %>% 
  mutate(accuracy = predicted_category == category,
         true_label = category,
         predicted_label = predicted_category) %>% 
  select(accuracy,age,subject_name,sub,true_label,predicted_label) %>% 
  mutate(classifcation='category')


df_accuracy <-  rbind(cyto_accuracy,category_accuracy,age_accuracy)

```

