---
title: "Slope plus gestational age"
author: "Emily Kubota"
date: "10/08/2024"
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE}
library("tidyverse") # for all things tidyverse


# set the default ggplot theme 
theme_set(theme_classic())


```



```{r}
# Read in the data 

df = read_csv("../../data/endpoints.csv",
                       col_types = cols())

df_ages_bb = read_csv("../../data/bb_ages.csv",
                       col_types = cols())

df_ages_adults = read_csv("../../data/ages_adults.csv",
                       col_types = cols())

# correct for gestational age

df_ages_adults <-
df_ages_adults %>% 
  mutate(sessid = sub,
         corrected_age = age_days) %>% 
  select(sessid,corrected_age,age_days)

df_ages_bb <-
df_ages_bb %>% 
  mutate(sessid = paste0(ID,'/',timepoint),
         corrected_age = case_when(
           gestational_age < 40 ~ age - ((40 - gestational_age) * 7),
           .default = age),
         age_days = age) %>% 
  select(sessid,corrected_age,age_days)

df_ages <- rbind(df_ages_adults,df_ages_bb)


# Filter for LH 
df <- 
  df %>% 
  filter(hem == "lh")

df <- merge(df,df_ages, by.x = c("sessid","age_days"), by.y = c("sessid","age_days")) 


# translate corrected age to log scale & drop nas 

df <- 
  df %>% 
  mutate(log10corrected_age = log10(corrected_age)) %>% 
  drop_na()

```


```{r}

# Main Effect of Age for each fROI

froi_name = "pFus"

fit_compact_a <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ log10(corrected_age),.) 

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 


anova(fit_compact_a,fit_compact_b)

```

```{r}

froi_name = "pOTS"

fit_compact_a <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ log10(corrected_age),.) 

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 


anova(fit_compact_a,fit_compact_b) 

```


```{r}

froi_name = "PPA"

fit_compact_a <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ log10(corrected_age),.) 

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 


anova(fit_compact_a,fit_compact_b) 

```

```{r}

froi_name = "mFus"

fit_compact_a <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ log10(corrected_age),.) 

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 


anova(fit_compact_a,fit_compact_b) 

```

```{r}

froi_name = "OTS"

fit_compact_a <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ log10(corrected_age),.) 

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 


anova(fit_compact_a,fit_compact_b) 

```

```{r}

froi_name = "mOTS"

fit_compact_a <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ log10(corrected_age),.) 

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 


anova(fit_compact_a,fit_compact_b) 

```

```{r}
# Glasser ROI x age interaction for each fROI

froi_name = "pFus"

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 

fit_augmented <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi * log10(corrected_age),.) 


 anova(fit_compact_b,fit_augmented) 
```

```{r}

froi_name = "pOTS"

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 

fit_augmented <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi * log10(corrected_age),.) 


 anova(fit_compact_b,fit_augmented) 
```


```{r}

froi_name = "PPA"

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 

fit_augmented <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi * log10(corrected_age),.) 


 anova(fit_compact_b,fit_augmented) 
```

```{r}

froi_name = "mFus"

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 

fit_augmented <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi * log10(corrected_age),.) 


 anova(fit_compact_b,fit_augmented) 
```

```{r}

froi_name = "OTS"

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 

fit_augmented <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi * log10(corrected_age),.) 


 anova(fit_compact_b,fit_augmented) 
```

```{r}

froi_name = "mOTS"

fit_compact_b <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi + log10(corrected_age),.) 

fit_augmented <- df %>% 
  filter(froi == froi_name) %>% 
  lm(endpoint_density ~ glasser_roi * log10(corrected_age),.) 


 anova(fit_compact_b,fit_augmented) 
```