---
title: "Distance control"
author: "Emily Kubota"
date: "7/25/2024"
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE}
library("tidyverse") # for all things tidyverse
library("ggcorrplot")
library("viridis")


# set the default ggplot theme 
theme_set(theme_classic())


```

```{r}
# Read in the data 

df_dist = read_csv("../../data/physical_distance.csv",
                       col_types = cols())

df_classification = read_csv("../../data/distance_control.csv",
                       col_types = cols())

```

```{r}
df_dist_long <-
df_dist %>% 
  pivot_longer(cols = c("within_fg4","fg4_fg2"), 
               names_to = "Cytoarchitecture",
               values_to = "Distance")
```

```{r}
# Plot out physical distance between the control regions 

df_dist_long %>% 
  mutate(Cytoarchitecture = recode(Cytoarchitecture,
                                    'within_fg4' = 'Within',
                                    'fg4_fg2' = 'Between')) %>% 
  ggplot(aes(x=Cytoarchitecture,y=Distance)) +
  geom_violin() +
    stat_summary(fun = "mean",
                 geom = "point") +
    stat_summary(
      fun.data = "mean_se",
      geom = "linerange",
      size = 1,
      color = "black"
    ) +
  ylab("Distance (mm)") +
  geom_point(alpha = 0.2,
             position = position_jitter(width = 0.1,
                                        height = 0),
             size = 2) +
  theme(aspect.ratio = .75)


ggsave(
      filename = '../figures/5_distance_control/distance.png',
      width = 3,
      height = 3
    )
```
```{r}
# T-test comparing distance within/between cyto areas 

t.test(df_dist$within_fg4,df_dist$fg4_fg2,paired = TRUE)
```

```{r}
# confusion matrix 

row_names = c("FG2","FG4")
col_names = rev(row_names)

df_filtered <-
  df_classification %>% 
  mutate(true_label = recode(cyto, "2" = 'FG2', "4" = 'FG4'),
         predicted_label = recode(predicted_cyto, "2" = 'FG2', "4" = 'FG4'))

matrix_holder = matrix(, nrow = 2, ncol = 2)

for (i in 1:length(row_names)){
  for (j in 1:length(col_names)){
    n = sum((df_filtered$true_label == col_names[j]) & (df_filtered$predicted_label == row_names[i]))
    matrix_holder[i,j] = n/sum(df_filtered$true_label == col_names[j])*100
  }
}

rownames(matrix_holder) <- c("FG2","FG4")
colnames(matrix_holder) <- rev(c("FG2","FG4"))
matrix_holder %>%
    ggcorrplot(lab = TRUE,
           lab_size = 2,
      tl.cex = 12) +
  scale_fill_viridis(limits = c(0, 100),
                     name = "Percentage") 

ggsave(
      filename = '../figures/5_distance_control/confusion_matrix.png',
      width = 3,
      height = 3
    )

```

```{r}
# Plot classification accuracy 

df_classification <-
  df_classification %>% 
  mutate(Accuracy = as.numeric(cyto == predicted_cyto),
         Cytoarchitecture = as.factor(cyto))

df_classification %>% 
  mutate(Cytoarchitecture = recode(Cytoarchitecture,
                                   '2' = 'FG2',
                                   '4' = 'FG4')) %>% 
  ggplot(aes(x=Cytoarchitecture,y=Accuracy,fill=Cytoarchitecture)) +
    stat_summary(fun = "mean",
                 geom = "bar") +
    stat_summary(
      fun.data = "mean_se",
      geom = "linerange",
      size = 1,
      color = "black"
    ) +
  scale_fill_manual(values =c("cyan","magenta")) +
  theme(aspect.ratio = .75,
        legend.position = "none") +
  geom_hline(yintercept = .5,linetype = 2)

ggsave(
      filename = '../figures/5_distance_control/classification_accuracy.png',
      width = 3,
      height = 3
    )
```

```{r}
# T-test to test if classification is above chance

df_accuracy_by_session <-
df_classification %>% 
  group_by(sub) %>% 
  summarize(Accuracy = mean(Accuracy))

t.test(df_accuracy_by_session$Accuracy,mu = .5)
```

```{r}
# Calculate overall mean + sd accuracy 

means <-
df_accuracy_by_session %>% 
  summarize(mean_accuracy = mean(Accuracy),
            sd_accuracy = sd(Accuracy))
```

